<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JMdict [
<!ELEMENT JMdict (entry*)>
<!--                                                                   -->
<!ELEMENT entry (ent_seq, k_ele*, r_ele+, sense+)>
	<!-- Entries consist of kanji elements, reading elements, 
	general information and sense elements. Each entry must have at 
	least one reading element and one sense element. Others are optional.
	-->
<!ELEMENT ent_seq (#PCDATA)>
	<!-- A unique numeric sequence number for each entry
	-->
<!ELEMENT k_ele (keb, ke_inf*, ke_pri*)>
	<!-- The kanji element, or in its absence, the reading element, is 
	the defining component of each entry.
	The overwhelming majority of entries will have a single kanji
	element associated with a word in Japanese. Where there are 
	multiple kanji elements within an entry, they will be orthographical
	variants of the same word, either using variations in okurigana, or
	alternative and equivalent kanji. Common "mis-spellings" may be 
	included, provided they are associated with appropriate information
	fields. Synonyms are not included; they may be indicated in the
	cross-reference field associated with the sense element.
	-->
<!ELEMENT keb (#PCDATA)>
	<!-- This element will contain a word or short phrase in Japanese 
	which is written using at least one non-kana character (usually kanji,
	but can be other characters). The valid characters are
	kanji, kana, related characters such as chouon and kurikaeshi, and
	in exceptional cases, letters from other alphabets.
	-->
<!ELEMENT ke_inf (#PCDATA)>
	<!-- This is a coded information field related specifically to the 
	orthography of the keb, and will typically indicate some unusual
	aspect, such as okurigana irregularity.
	-->
<!ELEMENT ke_pri (#PCDATA)>
	<!-- This and the equivalent re_pri field are provided to record
	information about the relative priority of the entry,  and consist
	of codes indicating the word appears in various references which
	can be taken as an indication of the frequency with which the word
	is used. This field is intended for use either by applications which 
	want to concentrate on entries of  a particular priority, or to 
	generate subset files. 
	The current values in this field are:
	- news1/2: appears in the "wordfreq" file compiled by Alexandre Girardi
	from the Mainichi Shimbun. (See the Monash ftp archive for a copy.)
	Words in the first 12,000 in that file are marked "news1" and words 
	in the second 12,000 are marked "news2".
	- ichi1/2: appears in the "Ichimango goi bunruishuu", Senmon Kyouiku 
	Publishing, Tokyo, 1998.  (The entries marked "ichi2" were
	demoted from ichi1 because they were observed to have low
	frequencies in the WWW and newspapers.)
	- spec1 and spec2: a small number of words use this marker when they 
	are detected as being common, but are not included in other lists.
	- gai1/2: common loanwords, based on the wordfreq file.
	- nfxx: this is an indicator of frequency-of-use ranking in the
	wordfreq file. "xx" is the number of the set of 500 words in which
	the entry can be found, with "01" assigned to the first 500, "02"
	to the second, and so on. (The entries with news1, ichi1, spec1 and 
	gai1 values are marked with a "(P)" in the EDICT and EDICT2
	files.)

	The reason both the kanji and reading elements are tagged is because 
	on occasions a priority is only associated with a particular
	kanji/reading pair.
	-->
<!--                                                                   -->
<!ELEMENT r_ele (reb, re_nokanji?, re_restr*, re_inf*, re_pri*)>
	<!-- The reading element typically contains the valid readings
	of the word(s) in the kanji element using modern kanadzukai. 
	Where there are multiple reading elements, they will typically be
	alternative readings of the kanji element. In the absence of a 
	kanji element, i.e. in the case of a word or phrase written
	entirely in kana, these elements will define the entry.
	-->
<!ELEMENT reb (#PCDATA)>
	<!-- this element content is restricted to kana and related
	characters such as chouon and kurikaeshi. Kana usage will be
	consistent between the keb and reb elements; e.g. if the keb
	contains katakana, so too will the reb.
	-->
<!ELEMENT re_nokanji (#PCDATA)>
	<!-- This element, which will usually have a null value, indicates
	that the reb, while associated with the keb, cannot be regarded
	as a true reading of the kanji. It is typically used for words
	such as foreign place names, gairaigo which can be in kanji or
	katakana, etc.
	-->
<!ELEMENT re_restr (#PCDATA)>
	<!-- This element is used to indicate when the reading only applies
	to a subset of the keb elements in the entry. In its absence, all
	readings apply to all kanji elements. The contents of this element 
	must exactly match those of one of the keb elements.
	-->
<!ELEMENT re_inf (#PCDATA)>
	<!-- General coded information pertaining to the specific reading.
	Typically it will be used to indicate some unusual aspect of 
	the reading. -->
<!ELEMENT re_pri (#PCDATA)>
	<!-- See the comment on ke_pri above. -->
<!--                                                                   -->
<!ELEMENT sense (stagk*, stagr*, pos*, xref*, ant*, field*, misc*, s_inf*, lsource*, dial*, gloss*)>
	<!-- The sense element will record the translational equivalent
	of the Japanese word, plus other related information. Where there
	are several distinctly different meanings of the word, multiple
	sense elements will be employed.
	-->
<!ELEMENT stagk (#PCDATA)>
<!ELEMENT stagr (#PCDATA)>
	<!-- These elements, if present, indicate that the sense is restricted
	to the lexeme represented by the keb and/or reb. -->
<!ELEMENT xref (#PCDATA)*>
	<!-- This element is used to indicate a cross-reference to another
	entry with a similar or related meaning or sense. The content of
	this element is typically a keb or reb element in another entry. In some
	cases a keb will be followed by a reb and/or a sense number to provide
	a precise target for the cross-reference. Where this happens, a JIS
	"centre-dot" (0x2126) is placed between the components of the 
	cross-reference.
	-->
<!ELEMENT ant (#PCDATA)*>
	<!-- This element is used to indicate another entry which is an
	antonym of the current entry/sense. The content of this element
	must exactly match that of a keb or reb element in another entry.
	-->
<!ELEMENT pos (#PCDATA)>
	<!-- Part-of-speech information about the entry/sense. Should use 
	appropriate entity codes. In general where there are multiple senses
	in an entry, the part-of-speech of an earlier sense will apply to
	later senses unless there is a new part-of-speech indicated.
	-->
<!ELEMENT field (#PCDATA)>
	<!-- Information about the field of application of the entry/sense. 
	When absent, general application is implied. Entity coding for 
	specific fields of application. -->
<!ELEMENT misc (#PCDATA)>
	<!-- This element is used for other relevant information about 
	the entry/sense. As with part-of-speech, information will usually
	apply to several senses.
	-->
<!ELEMENT lsource (#PCDATA)>
	<!-- This element records the information about the source
	language(s) of a loan-word/gairaigo. If the source language is other 
	than English, the language is indicated by the xml:lang attribute.
	The element value (if any) is the source word or phrase.
	-->
<!ATTLIST lsource xml:lang CDATA "eng">
	<!-- The xml:lang attribute defines the language(s) from which
	a loanword is drawn.  It will be coded using the three-letter language 
	code from the ISO 639-2 standard. When absent, the value "eng" (i.e. 
	English) is the default value. The bibliographic (B) codes are used. -->
<!ATTLIST lsource ls_type CDATA #IMPLIED>
	<!-- The ls_type attribute indicates whether the lsource element
	fully or partially describes the source word or phrase of the
	loanword. If absent, it will have the implied value of "full".
	Otherwise it will contain "part".  -->
<!ATTLIST lsource ls_wasei CDATA #IMPLIED>
	<!-- The ls_wasei attribute indicates that the Japanese word
	has been constructed from words in the source language, and
	not from an actual phrase in that language. Most commonly used to
	indicate "waseieigo". -->
<!ELEMENT dial (#PCDATA)>
	<!-- For words specifically associated with regional dialects in
	Japanese, the entity code for that dialect, e.g. ksb for Kansaiben.
	-->
<!ELEMENT gloss (#PCDATA | pri)*>
	<!-- Within each sense will be one or more "glosses", i.e. 
	target-language words or phrases which are equivalents to the 
	Japanese word. This element would normally be present, however it 
	may be omitted in entries which are purely for a cross-reference.
	-->
<!ATTLIST gloss xml:lang CDATA "eng">
	<!-- The xml:lang attribute defines the target language of the
	gloss. It will be coded using the three-letter language code from
	the ISO 639 standard. When absent, the value "eng" (i.e. English)
	is the default value. -->
<!ATTLIST gloss g_gend CDATA #IMPLIED>
	<!-- The g_gend attribute defines the gender of the gloss (typically
	a noun in the target language. When absent, the gender is either
	not relevant or has yet to be provided.
	-->
<!ELEMENT pri (#PCDATA)>
	<!-- These elements highlight particular target-language words which 
	are strongly associated with the Japanese word. The purpose is to 
	establish a set of target-language words which can effectively be 
	used as head-words in a reverse target-language/Japanese relationship.
	-->
<!ELEMENT s_inf (#PCDATA)>
	<!-- The sense-information elements provided for additional
	information to be recorded about a sense. Typical usage would
	be to indicate such things as level of currency of a sense, the
	regional variations, etc.
	-->
<!-- The following entity codes are used for common elements within the
various information fields.
-->
<!ENTITY MA "martial arts term">
<!ENTITY X "rude or X-rated term (not displayed in educational software)">
<!ENTITY abbr "abbreviation">
<!ENTITY adj-i "adjective (keiyoushi)">
<!ENTITY adj-ix "adjective (keiyoushi) - yoi/ii class">
<!ENTITY adj-na "adjectival nouns or quasi-adjectives (keiyodoshi)">
<!ENTITY adj-no "nouns which may take the genitive case particle `no'">
<!ENTITY adj-pn "pre-noun adjectival (rentaishi)">
<!ENTITY adj-t "`taru' adjective">
<!ENTITY adj-f "noun or verb acting prenominally">
<!ENTITY adv "adverb (fukushi)">
<!ENTITY adv-to "adverb taking the `to' particle">
<!ENTITY arch "archaism">
<!ENTITY ateji "ateji (phonetic) reading">
<!ENTITY aux "auxiliary">
<!ENTITY aux-v "auxiliary verb">
<!ENTITY aux-adj "auxiliary adjective">
<!ENTITY Buddh "Buddhist term">
<!ENTITY chem "chemistry term">
<!ENTITY chn "children's language">
<!ENTITY col "colloquialism">
<!ENTITY comp "computer terminology">
<!ENTITY conj "conjunction">
<!ENTITY cop-da "copula">
<!ENTITY ctr "counter">
<!ENTITY derog "derogatory">
<!ENTITY eK "exclusively kanji">
<!ENTITY ek "exclusively kana">
<!ENTITY exp "expressions (phrases, clauses, etc.)">
<!ENTITY fam "familiar language">
<!ENTITY fem "female term or language">
<!ENTITY food "food term">
<!ENTITY geom "geometry term">
<!ENTITY gikun "gikun (meaning as reading) or jukujikun (special kanji reading)">
<!ENTITY hon "honorific or respectful (sonkeigo) language">
<!ENTITY hum "humble (kenjougo) language">
<!ENTITY iK "word containing irregular kanji usage">
<!ENTITY id "idiomatic expression">
<!ENTITY ik "word containing irregular kana usage">
<!ENTITY int "interjection (kandoushi)">
<!ENTITY io "irregular okurigana usage">
<!ENTITY iv "irregular verb">
<!ENTITY ling "linguistics terminology">
<!ENTITY m-sl "manga slang">
<!ENTITY male "male term or language">
<!ENTITY male-sl "male slang">
<!ENTITY math "mathematics">
<!ENTITY mil "military">
<!ENTITY n "noun (common) (futsuumeishi)">
<!ENTITY n-adv "adverbial noun (fukushitekimeishi)">
<!ENTITY n-suf "noun, used as a suffix">
<!ENTITY n-pref "noun, used as a prefix">
<!ENTITY n-t "noun (temporal) (jisoumeishi)">
<!ENTITY num "numeric">
<!ENTITY oK "word containing out-dated kanji">
<!ENTITY obs "obsolete term">
<!ENTITY obsc "obscure term">
<!ENTITY ok "out-dated or obsolete kana usage">
<!ENTITY oik "old or irregular kana form">
<!ENTITY on-mim "onomatopoeic or mimetic word">
<!ENTITY pn "pronoun">
<!ENTITY poet "poetical term">
<!ENTITY pol "polite (teineigo) language">
<!ENTITY pref "prefix">
<!ENTITY proverb "proverb">
<!ENTITY prt "particle">
<!ENTITY physics "physics terminology">
<!ENTITY rare "rare">
<!ENTITY sens "sensitive">
<!ENTITY sl "slang">
<!ENTITY suf "suffix">
<!ENTITY uK "word usually written using kanji alone">
<!ENTITY uk "word usually written using kana alone">
<!ENTITY unc "unclassified">
<!ENTITY yoji "yojijukugo">
<!ENTITY v1 "Ichidan verb">
<!ENTITY v1-s "Ichidan verb - kureru special class">
<!ENTITY v2a-s "Nidan verb with 'u' ending (archaic)">
<!ENTITY v4h "Yodan verb with `hu/fu' ending (archaic)">
<!ENTITY v4r "Yodan verb with `ru' ending (archaic)">
<!ENTITY v5aru "Godan verb - -aru special class">
<!ENTITY v5b "Godan verb with `bu' ending">
<!ENTITY v5g "Godan verb with `gu' ending">
<!ENTITY v5k "Godan verb with `ku' ending">
<!ENTITY v5k-s "Godan verb - Iku/Yuku special class">
<!ENTITY v5m "Godan verb with `mu' ending">
<!ENTITY v5n "Godan verb with `nu' ending">
<!ENTITY v5r "Godan verb with `ru' ending">
<!ENTITY v5r-i "Godan verb with `ru' ending (irregular verb)">
<!ENTITY v5s "Godan verb with `su' ending">
<!ENTITY v5t "Godan verb with `tsu' ending">
<!ENTITY v5u "Godan verb with `u' ending">
<!ENTITY v5u-s "Godan verb with `u' ending (special class)">
<!ENTITY v5uru "Godan verb - Uru old class verb (old form of Eru)">
<!ENTITY vz "Ichidan verb - zuru verb (alternative form of -jiru verbs)">
<!ENTITY vi "intransitive verb">
<!ENTITY vk "Kuru verb - special class">
<!ENTITY vn "irregular nu verb">
<!ENTITY vr "irregular ru verb, plain form ends with -ri">
<!ENTITY vs "noun or participle which takes the aux. verb suru">
<!ENTITY vs-c "su verb - precursor to the modern suru">
<!ENTITY vs-s "suru verb - special class">
<!ENTITY vs-i "suru verb - irregular">
<!ENTITY kyb "Kyoto-ben">
<!ENTITY osb "Osaka-ben">
<!ENTITY ksb "Kansai-ben">
<!ENTITY ktb "Kantou-ben">
<!ENTITY tsb "Tosa-ben">
<!ENTITY thb "Touhoku-ben">
<!ENTITY tsug "Tsugaru-ben">
<!ENTITY kyu "Kyuushuu-ben">
<!ENTITY rkb "Ryuukyuu-ben">
<!ENTITY nab "Nagano-ben">
<!ENTITY hob "Hokkaido-ben">
<!ENTITY vt "transitive verb">
<!ENTITY vulg "vulgar expression or word">
<!ENTITY adj-kari "`kari' adjective (archaic)">
<!ENTITY adj-ku "`ku' adjective (archaic)">
<!ENTITY adj-shiku "`shiku' adjective (archaic)">
<!ENTITY adj-nari "archaic/formal form of na-adjective">
<!ENTITY n-pr "proper noun">
<!ENTITY v-unspec "verb unspecified">
<!ENTITY v4k "Yodan verb with `ku' ending (archaic)">
<!ENTITY v4g "Yodan verb with `gu' ending (archaic)">
<!ENTITY v4s "Yodan verb with `su' ending (archaic)">
<!ENTITY v4t "Yodan verb with `tsu' ending (archaic)">
<!ENTITY v4n "Yodan verb with `nu' ending (archaic)">
<!ENTITY v4b "Yodan verb with `bu' ending (archaic)">
<!ENTITY v4m "Yodan verb with `mu' ending (archaic)">
<!ENTITY v2k-k "Nidan verb (upper class) with `ku' ending (archaic)">
<!ENTITY v2g-k "Nidan verb (upper class) with `gu' ending (archaic)">
<!ENTITY v2t-k "Nidan verb (upper class) with `tsu' ending (archaic)">
<!ENTITY v2d-k "Nidan verb (upper class) with `dzu' ending (archaic)">
<!ENTITY v2h-k "Nidan verb (upper class) with `hu/fu' ending (archaic)">
<!ENTITY v2b-k "Nidan verb (upper class) with `bu' ending (archaic)">
<!ENTITY v2m-k "Nidan verb (upper class) with `mu' ending (archaic)">
<!ENTITY v2y-k "Nidan verb (upper class) with `yu' ending (archaic)">
<!ENTITY v2r-k "Nidan verb (upper class) with `ru' ending (archaic)">
<!ENTITY v2k-s "Nidan verb (lower class) with `ku' ending (archaic)">
<!ENTITY v2g-s "Nidan verb (lower class) with `gu' ending (archaic)">
<!ENTITY v2s-s "Nidan verb (lower class) with `su' ending (archaic)">
<!ENTITY v2z-s "Nidan verb (lower class) with `zu' ending (archaic)">
<!ENTITY v2t-s "Nidan verb (lower class) with `tsu' ending (archaic)">
<!ENTITY v2d-s "Nidan verb (lower class) with `dzu' ending (archaic)">
<!ENTITY v2n-s "Nidan verb (lower class) with `nu' ending (archaic)">
<!ENTITY v2h-s "Nidan verb (lower class) with `hu/fu' ending (archaic)">
<!ENTITY v2b-s "Nidan verb (lower class) with `bu' ending (archaic)">
<!ENTITY v2m-s "Nidan verb (lower class) with `mu' ending (archaic)">
<!ENTITY v2y-s "Nidan verb (lower class) with `yu' ending (archaic)">
<!ENTITY v2r-s "Nidan verb (lower class) with `ru' ending (archaic)">
<!ENTITY v2w-s "Nidan verb (lower class) with `u' ending and `we' conjugation (archaic)">
<!ENTITY archit "architecture term">
<!ENTITY astron "astronomy, etc. term">
<!ENTITY baseb "baseball term">
<!ENTITY biol "biology term">
<!ENTITY bot "botany term">
<!ENTITY bus "business term">
<!ENTITY econ "economics term">
<!ENTITY engr "engineering term">
<!ENTITY finc "finance term">
<!ENTITY geol "geology, etc. term">
<!ENTITY law "law, etc. term">
<!ENTITY mahj "mahjong term">
<!ENTITY med "medicine, etc. term">
<!ENTITY music "music term">
<!ENTITY Shinto "Shinto term">
<!ENTITY shogi "shogi term">
<!ENTITY sports "sports term">
<!ENTITY sumo "sumo term">
<!ENTITY zool "zoology term">
<!ENTITY joc "jocular, humorous term">
<!ENTITY anat "anatomical term">
]>
<!-- Mini version of JMDict for testing purpose -->
<JMdict>
<entry>
<ent_seq>1000000</ent_seq>
<r_ele>
<reb>ヽ</reb>
</r_ele>
<r_ele>
<reb>くりかえし</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>repetition mark in katakana</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000010</ent_seq>
<r_ele>
<reb>ヾ</reb>
</r_ele>
<r_ele>
<reb>くりかえし</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>voiced repetition mark in katakana</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000020</ent_seq>
<r_ele>
<reb>ゝ</reb>
</r_ele>
<r_ele>
<reb>くりかえし</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>repetition mark in hiragana</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000030</ent_seq>
<r_ele>
<reb>ゞ</reb>
</r_ele>
<r_ele>
<reb>くりかえし</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>voiced repetition mark in hiragana</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000040</ent_seq>
<k_ele>
<keb>〃</keb>
</k_ele>
<r_ele>
<reb>おなじ</reb>
</r_ele>
<r_ele>
<reb>おなじく</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>ditto mark</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000050</ent_seq>
<k_ele>
<keb>仝</keb>
</k_ele>
<r_ele>
<reb>どうじょう</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>"as above" mark</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000060</ent_seq>
<k_ele>
<keb>々</keb>
</k_ele>
<r_ele>
<reb>くりかえし</reb>
</r_ele>
<r_ele>
<reb>おなじ</reb>
</r_ele>
<r_ele>
<reb>おなじく</reb>
</r_ele>
<r_ele>
<reb>のま</reb>
</r_ele>
<r_ele>
<reb>どうのじてん</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>repetition of kanji (sometimes voiced)</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000080</ent_seq>
<k_ele>
<keb>漢数字ゼロ</keb>
</k_ele>
<r_ele>
<reb>かんすうじゼロ</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<xref>○・まる・1</xref>
<xref>漢数字</xref>
<gloss>"kanji" zero</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000090</ent_seq>
<k_ele>
<keb>○</keb>
</k_ele>
<k_ele>
<keb>〇</keb>
</k_ele>
<r_ele>
<reb>まる</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<xref>丸・まる・1</xref>
<gloss>circle (sometimes used for zero)</gloss>
</sense>
<sense>
<xref>二重丸・にじゅうまる</xref>
<ant>×・ばつ・1</ant>
<gloss>'correct' (when marking)</gloss>
</sense>
<sense>
<xref>〇〇・まるまる・1</xref>
<gloss>symbol used as a placeholder (either because a number of other words could be used in that position, or because of censorship)</gloss>
</sense>
<sense>
<xref>句点</xref>
<gloss>period</gloss>
<gloss>full stop</gloss>
</sense>
<sense>
<xref>半濁点</xref>
<gloss>maru mark</gloss>
<gloss>semivoiced sound</gloss>
<gloss>p-sound</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000100</ent_seq>
<k_ele>
<keb>ＡＢＣ順</keb>
</k_ele>
<r_ele>
<reb>エービーシーじゅん</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>alphabetical order</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000110</ent_seq>
<k_ele>
<keb>ＣＤプレーヤー</keb>
<ke_pri>spec1</ke_pri>
</k_ele>
<k_ele>
<keb>ＣＤプレイヤー</keb>
</k_ele>
<r_ele>
<reb>シーディープレーヤー</reb>
<re_restr>ＣＤプレーヤー</re_restr>
<re_pri>spec1</re_pri>
</r_ele>
<r_ele>
<reb>シーディープレイヤー</reb>
<re_restr>ＣＤプレイヤー</re_restr>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>CD player</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000130</ent_seq>
<k_ele>
<keb>Ｎ響</keb>
</k_ele>
<r_ele>
<reb>エヌきょう</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<misc>&abbr;</misc>
<gloss>NHK Symphony Orchestra</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000140</ent_seq>
<k_ele>
<keb>Ｏバック</keb>
</k_ele>
<r_ele>
<reb>オーバック</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>O-back</gloss>
<gloss>skirt with peek-a-boo hole in rump</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000150</ent_seq>
<k_ele>
<keb>ＲＳ２３２ケーブル</keb>
</k_ele>
<r_ele>
<reb>アールエスにさんにケーブル</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>rs232 cable</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000160</ent_seq>
<k_ele>
<keb>Ｔシャツ</keb>
</k_ele>
<r_ele>
<reb>ティーシャツ</reb>
<re_pri>spec1</re_pri>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>T-shirt</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000170</ent_seq>
<k_ele>
<keb>Ｔバック</keb>
<ke_pri>spec1</ke_pri>
</k_ele>
<r_ele>
<reb>ティーバック</reb>
<re_pri>spec1</re_pri>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>T-back</gloss>
<gloss>bikini thong</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000200</ent_seq>
<k_ele>
<keb>あうんの呼吸</keb>
</k_ele>
<k_ele>
<keb>阿吽の呼吸</keb>
</k_ele>
<r_ele>
<reb>あうんのこきゅう</reb>
</r_ele>
<sense>
<pos>&exp;</pos>
<pos>&n;</pos>
<gloss>the harmonizing, mentally and physically, of two parties engaged in an activity</gloss>
<gloss>singing from the same hymn-sheet</gloss>
<gloss>dancing to the same beat</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000210</ent_seq>
<r_ele>
<reb>あおば</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<xref>やまびこ</xref>
<misc>&obs;</misc>
<gloss>(former) regular (stops at every station) Tohoku-line Shinkansen</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000220</ent_seq>
<k_ele>
<keb>明白</keb>
<ke_pri>ichi1</ke_pri>
<ke_pri>news1</ke_pri>
<ke_pri>nf10</ke_pri>
</k_ele>
<r_ele>
<reb>めいはく</reb>
<re_pri>ichi1</re_pri>
<re_pri>news1</re_pri>
<re_pri>nf10</re_pri>
</r_ele>
<sense>
<pos>&adj-na;</pos>
<gloss>obvious</gloss>
<gloss>clear</gloss>
<gloss>plain</gloss>
<gloss>evident</gloss>
<gloss>apparent</gloss>
<gloss>explicit</gloss>
<gloss>overt</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000225</ent_seq>
<k_ele>
<keb>明白</keb>
<ke_inf>&ateji;</ke_inf>
</k_ele>
<k_ele>
<keb>偸閑</keb>
<ke_inf>&ateji;</ke_inf>
</k_ele>
<k_ele>
<keb>白地</keb>
<ke_inf>&ateji;</ke_inf>
</k_ele>
<r_ele>
<reb>あからさま</reb>
</r_ele>
<sense>
<pos>&adj-na;</pos>
<pos>&adj-no;</pos>
<misc>&uk;</misc>
<gloss>plain</gloss>
<gloss>frank</gloss>
<gloss>candid</gloss>
<gloss>open</gloss>
<gloss>direct</gloss>
<gloss>straightforward</gloss>
<gloss>unabashed</gloss>
<gloss>blatant</gloss>
<gloss>flagrant</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000230</ent_seq>
<k_ele>
<keb>明かん</keb>
</k_ele>
<r_ele>
<reb>あかん</reb>
</r_ele>
<r_ele>
<reb>アカン</reb>
<re_nokanji/>
</r_ele>
<sense>
<pos>&exp;</pos>
<misc>&uk;</misc>
<dial>&ksb;</dial>
<gloss>useless</gloss>
<gloss>no good</gloss>
<gloss>hopeless</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000260</ent_seq>
<k_ele>
<keb>悪どい</keb>
<ke_inf>&iK;</ke_inf>
</k_ele>
<r_ele>
<reb>あくどい</reb>
</r_ele>
<sense>
<pos>&adj-i;</pos>
<misc>&uk;</misc>
<gloss>gaudy</gloss>
<gloss>showy</gloss>
<gloss>excessive</gloss>
</sense>
<sense>
<gloss>crooked</gloss>
<gloss>vicious</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000280</ent_seq>
<k_ele>
<keb>論う</keb>
</k_ele>
<r_ele>
<reb>あげつらう</reb>
</r_ele>
<sense>
<pos>&v5u;</pos>
<pos>&vt;</pos>
<misc>&uk;</misc>
<gloss>to discuss</gloss>
</sense>
<sense>
<gloss>to find fault with</gloss>
<gloss>to criticize</gloss>
<gloss>to criticise</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000290</ent_seq>
<r_ele>
<reb>あさひ</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<gloss>Jouetsu line express Shinkansen</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000300</ent_seq>
<r_ele>
<reb>あしらう</reb>
</r_ele>
<sense>
<pos>&v5u;</pos>
<pos>&vt;</pos>
<gloss>to arrange</gloss>
<gloss>to treat</gloss>
<gloss>to handle</gloss>
<gloss>to deal with</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000310</ent_seq>
<k_ele>
<keb>馬酔木</keb>
</k_ele>
<r_ele>
<reb>あせび</reb>
</r_ele>
<r_ele>
<reb>あしび</reb>
</r_ele>
<r_ele>
<reb>あせぼ</reb>
</r_ele>
<r_ele>
<reb>あせぶ</reb>
</r_ele>
<r_ele>
<reb>アセビ</reb>
<re_nokanji/>
</r_ele>
<sense>
<pos>&n;</pos>
<misc>&uk;</misc>
<gloss>Japanese andromeda (Pieris japonica)</gloss>
<gloss>lily-of-the-valley</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000320</ent_seq>
<k_ele>
<keb>彼処</keb>
<ke_pri>ichi1</ke_pri>
</k_ele>
<k_ele>
<keb>彼所</keb>
</k_ele>
<r_ele>
<reb>あそこ</reb>
<re_pri>ichi1</re_pri>
</r_ele>
<r_ele>
<reb>あすこ</reb>
</r_ele>
<r_ele>
<reb>かしこ</reb>
</r_ele>
<r_ele>
<reb>あしこ</reb>
<re_inf>&ok;</re_inf>
</r_ele>
<r_ele>
<reb>あこ</reb>
<re_inf>&ok;</re_inf>
</r_ele>
<sense>
<pos>&pn;</pos>
<pos>&adj-no;</pos>
<xref>何処</xref>
<xref>此処</xref>
<xref>其処</xref>
<misc>&uk;</misc>
<gloss>there (place physically distant from both speaker and listener)</gloss>
<gloss>over there</gloss>
<gloss>that place</gloss>
<gloss>yonder</gloss>
</sense>
<sense>
<stagr>あそこ</stagr>
<stagr>あすこ</stagr>
<pos>&n;</pos>
<misc>&col;</misc>
<gloss>genitals</gloss>
</sense>
<sense>
<xref>あれほど</xref>
<gloss>that far (something psychologically distant from both speaker and listener)</gloss>
<gloss>that much</gloss>
<gloss>that point</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000360</ent_seq>
<r_ele>
<reb>あっさり</reb>
<re_pri>ichi1</re_pri>
</r_ele>
<sense>
<pos>&adv-to;</pos>
<pos>&vs;</pos>
<misc>&on-mim;</misc>
<gloss>easily</gloss>
<gloss>readily</gloss>
<gloss>quickly</gloss>
</sense>
<sense>
<misc>&on-mim;</misc>
<gloss>lightly (flavored food, applied makeup)</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000390</ent_seq>
<k_ele>
<keb>あっという間に</keb>
</k_ele>
<k_ele>
<keb>あっと言う間に</keb>
</k_ele>
<k_ele>
<keb>あっとゆう間に</keb>
</k_ele>
<r_ele>
<reb>あっというまに</reb>
<re_restr>あっという間に</re_restr>
<re_restr>あっと言う間に</re_restr>
</r_ele>
<r_ele>
<reb>あっとゆうまに</reb>
<re_restr>あっと言う間に</re_restr>
<re_restr>あっとゆう間に</re_restr>
</r_ele>
<sense>
<pos>&exp;</pos>
<gloss>just like that</gloss>
<gloss>in the twinkling of an eye</gloss>
<gloss>in the blink of an eye</gloss>
<gloss>in the time it takes to say "ah!"</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000400</ent_seq>
<r_ele>
<reb>あっぷあっぷ</reb>
</r_ele>
<sense>
<pos>&adv;</pos>
<pos>&n;</pos>
<pos>&vs;</pos>
<gloss>floundering while nearly drowning</gloss>
</sense>
<sense>
<gloss>suffering</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000410</ent_seq>
<r_ele>
<reb>あどけない</reb>
</r_ele>
<sense>
<pos>&adj-i;</pos>
<gloss>innocent</gloss>
<gloss>cherubic</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000420</ent_seq>
<k_ele>
<keb>彼の</keb>
<ke_pri>spec1</ke_pri>
</k_ele>
<r_ele>
<reb>あの</reb>
<re_pri>spec1</re_pri>
</r_ele>
<r_ele>
<reb>かの</reb>
</r_ele>
<sense>
<pos>&adj-pn;</pos>
<xref>何の・どの</xref>
<xref>此の</xref>
<xref>其の・1</xref>
<xref>彼・あれ・1</xref>
<misc>&uk;</misc>
<gloss>that (someone or something distant from both speaker and listener, or situation unfamiliar to both speaker and listener)</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000430</ent_seq>
<r_ele>
<reb>あのう</reb>
<re_pri>spec1</re_pri>
</r_ele>
<r_ele>
<reb>あの</reb>
<re_pri>spec1</re_pri>
</r_ele>
<r_ele>
<reb>あのー</reb>
</r_ele>
<sense>
<pos>&int;</pos>
<gloss>say</gloss>
<gloss>well</gloss>
<gloss>errr ...</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000440</ent_seq>
<k_ele>
<keb>あの人</keb>
</k_ele>
<k_ele>
<keb>彼の人</keb>
</k_ele>
<r_ele>
<reb>あのひと</reb>
</r_ele>
<sense>
<pos>&pn;</pos>
<pos>&adj-no;</pos>
<gloss>he</gloss>
<gloss>she</gloss>
<gloss>that person</gloss>
</sense>
<sense>
<misc>&arch;</misc>
<gloss>you</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000450</ent_seq>
<k_ele>
<keb>あの方</keb>
<ke_pri>spec1</ke_pri>
</k_ele>
<k_ele>
<keb>彼の方</keb>
</k_ele>
<r_ele>
<reb>あのかた</reb>
<re_pri>spec1</re_pri>
</r_ele>
<sense>
<pos>&pn;</pos>
<pos>&adj-no;</pos>
<misc>&hon;</misc>
<gloss>that gentleman (lady)</gloss>
<gloss>he</gloss>
<gloss>she</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000460</ent_seq>
<k_ele>
<keb>溢れる</keb>
</k_ele>
<r_ele>
<reb>あぶれる</reb>
</r_ele>
<sense>
<pos>&v1;</pos>
<pos>&vi;</pos>
<misc>&uk;</misc>
<gloss>to fail (in getting a job)</gloss>
<gloss>to miss out (at fishing, hunting, etc.)</gloss>
</sense>
<sense>
<misc>&uk;</misc>
<gloss>to be left out</gloss>
<gloss>to be crowded out</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000470</ent_seq>
<r_ele>
<reb>あべこべ</reb>
<re_pri>ichi1</re_pri>
</r_ele>
<sense>
<pos>&adj-na;</pos>
<pos>&n;</pos>
<misc>&on-mim;</misc>
<gloss>contrary</gloss>
<gloss>opposite</gloss>
<gloss>inverse</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000480</ent_seq>
<k_ele>
<keb>阿呆陀羅</keb>
</k_ele>
<r_ele>
<reb>あほんだら</reb>
</r_ele>
<r_ele>
<reb>あほだら</reb>
</r_ele>
<sense>
<pos>&n;</pos>
<misc>&uk;</misc>
<dial>&ksb;</dial>
<gloss>fool</gloss>
<gloss>oaf</gloss>
<gloss>airhead</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000490</ent_seq>
<k_ele>
<keb>甘子</keb>
</k_ele>
<k_ele>
<keb>天魚</keb>
</k_ele>
<k_ele>
<keb>雨子</keb>
</k_ele>
<r_ele>
<reb>あまご</reb>
</r_ele>
<r_ele>
<reb>アマゴ</reb>
<re_nokanji/>
</r_ele>
<sense>
<pos>&n;</pos>
<xref>皐月鱒</xref>
<misc>&uk;</misc>
<gloss>land-locked variety of red-spotted masu trout (Oncorhynchus masou ishikawae)</gloss>
<gloss>amago</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000500</ent_seq>
<r_ele>
<reb>あやす</reb>
</r_ele>
<sense>
<pos>&v5s;</pos>
<pos>&vt;</pos>
<gloss>to cuddle</gloss>
<gloss>to comfort</gloss>
<gloss>to rock</gloss>
<gloss>to soothe</gloss>
<gloss>to dandle</gloss>
<gloss>to humor</gloss>
<gloss>to humour</gloss>
<gloss>to lull</gloss>
</sense>
</entry>
<entry>
<ent_seq>1000510</ent_seq>
<r_ele>
<reb>あやふや</reb>
<re_pri>ichi1</re_pri>
</r_ele>
<sense>
<pos>&adj-na;</pos>
<pos>&n;</pos>
<misc>&on-mim;</misc>
<gloss>uncertain</gloss>
<gloss>vague</gloss>
<gloss>ambiguous</gloss>
</sense>
</entry>
<entry>